service: trabalho-fiap-lambda-2

provider:
  name: aws
  stage: dev
  runtime: python3.6
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:ChangeMessageVisibility
        - sqs:DeleteMessage
        - sqs:ReceiveMessage
        - sqs:SendMessage
        - sqs:GetQueueUrl
      Resource: "arn:aws:sqs:us-east-1:516773109411:fiap-lab-trabalho-final-dev"

functions:
  sqsHandler:
    handler: handler.handler
    events:
      - schedule:
        rate: rate(5 minutes)
        enable: false