service: trabalho-fiap-lambda-gateway-usuario # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.6

# you can overwrite defaults here
stage: production
functions:
  readCustomer:
    handler: handler.handler
    events:
      - http:
          path: usuarios/{usuario}
          method: get