service: layes-teste

provider:
  name: aws
  runtime: python3.7

package:
  exclude:
    - layer/++

layers:
  LayerDependencies:
    path: layer
    description: "learning layers"

functions:
  hello:
    handler: handler.hello
    layers:
      - {Ref: LayerDependenciesLambdaLayer}
   
    