service: trabalho-fiap-lambda-1

provider:
  name: aws
  stage: dev
  runtime: python3.6
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:ChangeMessageVisibility
        - sqs:DeleteMessage
        - sqs:ReceiveMessage
        - sqs:SendMessage
        - sqs:GetQueueUrl
      Resource: "arn:aws:sqs:us-east-1:*:fiap-lab-trabalho-final-principal*"

functions:
  buscarUsuario:
    handler: handler.buscarUsuario
    events:
      - http:
          path: usuarios/{usuario}
          method: get
  criarUsuario:
    handler: handler.criarUsuario
    events:
      - http:
          path: usuarios
          method: post