service: trabalho-fiap-lambda-3

provider:
  name: aws
  stage: dev
  runtime: python3.6
  timeout: 300
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:ChangeMessageVisibility
        - sqs:DeleteMessage
        - sqs:ReceiveMessage
        - sqs:SendMessage
        - sqs:GetQueueUrl
      Resource: "arn:aws:sqs:us-east-1:*:fiap-lab-trabalho-final-principal*"
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: "arn:aws:sns:us-east-1:*:lab-fiap-trabalho-final-topico*"


functions:
  snsHandler:
    handler: handler.handler
    events:
      - schedule:
        rate: rate(5 minutes)
        enable: false